### ISSUE TITLE
Boards for sale

### ISSUE THREAD

**Issue by riogrande75** [stephan192/hoermann_door#12]
I built 2 of these beauties with the boards from stephan192, before I noticed, that they don't work with my SupraMatic E2 doors.
Boards are fully assembled, FW is flashed, tested, so you just have to flash ESP32 with your settings again and you are good to go.
![20220911_102231](https://user-images.githubusercontent.com/28924474/189521017-c5e81973-74c0-47f4-9570-bd42a781a163.jpg)

**Comment by Jarda-cz** [comment]
Hello,
  I'm interested, if you have one left.

**Comment by Abildgren** [comment]
Im also interested if there is one left.

**Comment by riogrande75** [comment]
Ok, pls. send me your email adresses - I will contact you.

**Comment by Jarda-cz** [comment]
My email is jarda.moravec@gmail.com . Thank you!

**Comment by Abildgren** [comment]
> Ok, pls. send me your email adresses - I will contact you.

Github (a) Abildgren (.) dk

**Comment by johnreitan** [comment]
Any chance you could build a few more?

**Comment by LocalNic** [comment]
I am also interrested .. I also like to oder them directly from jlbpcb. but for that I might need a short documentation which files I need to have the PCB right, the parts and their placement I guess. 

Or like my precessors, just buy it from some talented Maker. ;) 
br

**Comment by MatthiasLohr** [comment]
> Any chance you could build a few more?

Same question from my side... Any chance?

**Comment by wallo66** [comment]
I´m also interrested to buy a board, ist it possible?

**Comment by threadstone83** [comment]
Me too. It would be nice if they could be bought.

**Comment by realdimik** [comment]
I have 3 extra for sale. If someone is still interesting, send me your email for contact.
![1713631266396](https://github.com/stephan192/hoermann_door/assets/29751341/723fa4a2-b38b-40a8-aa2c-c1685db03480)

**Comment by MatthiasLohr** [comment]
I'm interested, will write you an email shortly.

**Comment by johnreitan** [comment]
I'm too, will email too shortly

**Comment by MatthiasLohr** [comment]
Can't find your email address anywhere. In case you wanted our mail addresses instead: mine is mail@mlohr.com, would be great if you could contact me. Thanks!

**Comment by realdimik** [comment]
Now all 3 are sold out.
