### ISSUE TITLE
Garage door is "read only" using HMIP HAP1-HCP adapter on Promatic4...

### ISSUE THREAD

**Issue by pboschi** [stephan192/hoermann_door#15]
Hi, as suggested by you in https://github.com/stephan192/hoermann_door/issues/5#issuecomment-851629119 and @Abildgren in https://github.com/stephan192/hoermann_door/issues/14#issuecomment-1377003619, I tried the HMIP HAP1-HCP adapter to connect your device to a Promatic 4 motor.

Issues so far:
1) I had to "jump start" the device powering it from +24v accessories plug of the motor and not from the bus. There is no power on the bus of Promatic 4 motors until you start a bus scan. So (i think) the scan fails because the ESP32 isn't quick enough to boot, and so the HMIP HAP1-HCP adapter turns off and so does the ESP32. When the PCB is powered externally, the scan succeeds, and from this point on the bus remains powered, and the adapter HAP1-HCP remains always on (even you disconnect the PCB). Would have been nice to have a separate power in pin terminals on the PCB... And also the blue led, it turns on only for an istant when you give power, would have been nice to have it on permanently when device is powered. Anyway, once "jump started", it will work as-is (until maybe you reset the bus?).

2) The MQTT commands to open/close and turn on/off light do not work. The status report is OK and aligned with the real status of the door (e.g., if I open the door via remote, I see it on MQTT; but if I try to open it via MQTT, it doesn't work).

It's like the motor is "read only"... 

Do you have any suggestion?

![image](https://user-images.githubusercontent.com/14005124/213005492-8db891c6-af52-484a-afe7-9d7c566058bb.png)
![image](https://user-images.githubusercontent.com/14005124/213005532-603eefa5-f17a-4292-9bb0-83da86c28f41.png)

**Comment by stephan192** [comment]
I don't have any clue why it doesn't work. There can be a lot of reasons. My first guess would be timing issues between the board and the HAP1-HCP.
To dig deeper into to problem i would start with connecting an original UAP1 to test if an 100% Hoermann setup is working.

Due to the fact that i neither own a version 4 drive, nor an HAP1-HCP nor an UAP1 i can't really help you with this.
